CP_VRS AI: 16.0 DBGEN: 15.0 DATE: Sat Oct 4 09:00:00 2000
//
CL_LIB "STATION" "08/01/18 11:22:54" TEXT: EFB Template Library
//

// Lines below are generated by tool, all manual changes will be overwritten
//
// Elementary Function Block:  ANALOG_7
//
//                      ____________________
//                     |                    |
//                     |      ANALOG_7      |
//                     |                    |
//       AN_VAR_TBL ---| Var_TBL----Var_TBL |--- AN_VAR_TBL
//       AN_PAR_TBL ---| Par_TBL            |                    
//             UINT ---| LevTyp     Val_TBL |--- AN_VAL_TBL      
//             UINT ---| RawValue  Stat_TBL |--- AN_ST_TBLS_T    
//             UINT ---| MeaNum             |                    
//             BOOL ---| Failure            |                    
//             UINT ---| IncTyp       Error |--- UINT            
//                     |____________________|
//
// ANALOG_7
//
CL_EFB "ANALOG_7" "Analog" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 10 11 "08/01/18 11:22:54" TEXT: Processing analogue measurings
...TXT         - (When measuring is disabled then value is equal raw value)
...TXT         You can configuration:
...TXT            - number of max level
...TXT            - incredible conpensation
...TXT         - test duty
CL_FRM "Par_TBL" SHOWNAME POSL 3 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE AN_PAR_TBL TEXT: Analog parameters blocks table
CL_FRM "LevTyp" SHOWNAME POSL 4 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: LevType == number of max level
CL_FRM "RawValue" SHOWNAME POSL 5 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: Raw analog value
CL_FRM "MeaNum" SHOWNAME POSL 6 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: Number of maesuring
CL_FRM "Failure" SHOWNAME POSL 7 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Channel healty information. 0 is OK
CL_FRM "IncTyp" SHOWNAME POSL 8 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: IncType LSB=1 -> under; 1Bit=1 -> upper
CL_FRM "Istate" SHOWNAME POSR 1 FP_IO_OUTPUT FP_OUTP_INTERN_STATE FP_LOC_HIDDEN INTSTATE VAL: 28 TEXT: Internal State
CL_FRM "Var_TBL" SHOWNAME POSR 2 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE AN_VAR_TBL TEXT: Analog variables blocks table
CL_FRM "Val_TBL" SHOWNAME POSR 4 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE AN_VAL_TBL TEXT: Analog value register table
CL_FRM "Stat_TBL" SHOWNAME POSR 5 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE AN_ST_TBLS_T TEXT: Analog status register table
CL_FRM "Error" SHOWNAME POSR 8 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE UINT TEXT: Analog measuring diagnostic
CL_PRT extern"C"BOOL FB_CALL_CONV ANALOG_7(const PTR_AN_PAR_TBL,
...PRT const PTR_UINT,
...PRT const PTR_UINT,
...PRT const PTR_UINT,
...PRT const PTR_BOOL,
...PRT const PTR_UINT,
...PRT PTR_Istat_ANALOG_7,
...PRT PTR_AN_VAR_TBL,
...PRT PTR_AN_VAL_TBL,
...PRT PTR_AN_ST_TBLS_T,
...PRT PTR_UINT);
//
// Elementary Function Block:  ANFLTLIM
//
//                      ____________________
//                     |                    |
//                     |      ANFLTLIM      |
//                     |                    |
//             UINT ---| AnalogV  OutAnalog |--- UINT            
//             UINT ---| AnLimit            |                    
//                     |____________________|
//
// ANFLTLIM
//
CL_EFB "ANFLTLIM" "Analog" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 5 11 "08/01/18 11:22:54" TEXT: Analog value filtration.
CL_FRM "AnalogV" SHOWNAME POSL 2 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: Analog Input value 
CL_FRM "AnLimit" SHOWNAME POSL 3 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: Limit for the filtration
CL_FRM "Istate" SHOWNAME POSR 1 FP_IO_OUTPUT FP_OUTP_INTERN_STATE FP_LOC_HIDDEN INTSTATE VAL: 2 TEXT: Internal State
CL_FRM "OutAnalog" SHOWNAME POSR 2 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE UINT TEXT: Analog Output 
CL_PRT extern"C"BOOL FB_CALL_CONV ANFLTLIM(const PTR_UINT,
...PRT const PTR_UINT,
...PRT PTR_Istat_ANFLTLIM,
...PRT PTR_UINT);
//
// Elementary Function Block:  AN_CHDET
//
//                      ____________________
//                     |                    |
//                     |      AN_CHDET      |
//                     |                    |
//             UINT ---| Offset    ChdetTBL |--- ST_TBL_T        
//                     |           AnStaTBL |--- AN_ST_TBLS_T    
//             UINT ---| Up_Lim             |                    
//             UINT ---| Dw_Lim             |                    
//                     |            FirstCh |--- UINT            
//             UINT ---| x_to_1       ChDet |--- BOOL            
//                     |____________________|
//
// AN_CHDET
//
CL_EFB "AN_CHDET" "Analog" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 9 10 "08/01/18 11:00:21" TEXT: Change detection in the analog parameter trable
CL_FRM "Offset" SHOWNAME POSL 2 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: 	Offset in the table
CL_FRM "Up_Lim" SHOWNAME POSL 4 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: 	Change detection up limit
CL_FRM "Dw_Lim" SHOWNAME POSL 5 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: 	Change detection down limit
CL_FRM "x_to_1" SHOWNAME POSL 7 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: 	x bit change together
CL_FRM "ChdetTBL" SHOWNAME POSR 2 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE ST_TBL_T TEXT:   Anbalog change detection table
CL_FRM "AnStaTBL" SHOWNAME POSR 3 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE AN_ST_TBLS_T TEXT:   Analog status table
CL_FRM "FirstCh" SHOWNAME POSR 6 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE UINT TEXT:   number First change in the table
CL_FRM "ChDet" SHOWNAME POSR 7 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: 	Have change detection in the field
CL_PRT extern"C"BOOL FB_CALL_CONV AN_CHDET(const PTR_UINT,
...PRT const PTR_UINT,
...PRT const PTR_UINT,
...PRT const PTR_UINT,
...PRT PTR_ST_TBL_T,
...PRT PTR_AN_ST_TBLS_T,
...PRT PTR_UINT,
...PRT PTR_BOOL);
//
// Elementary Function Block:  AN_LIM_7
//
//                      ____________________
//                     |                    |
//                     |      AN_LIM_7      |
//                     |                    |
//             WORD ---| ANStat    MaxAlarm |--- BOOL            
//                     |         MaxWarning |--- BOOL            
//                     |         MinWarning |--- BOOL            
//                     |           MinAlarm |--- BOOL            
//                     |                    |                    
//                     |            Invalid |--- BOOL            
//                     |____________________|
//
// AN_LIM_7
//
CL_EFB "AN_LIM_7" "Analog" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 9 10 "08/01/18 11:00:21" TEXT: Analog limits from status
...TXT             - test duty
CL_FRM "ANStat" SHOWNAME POSL 2 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE WORD TEXT: analog status word
CL_FRM "MaxAlarm" SHOWNAME POSR 2 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: max alarm limit
CL_FRM "MaxWarning" SHOWNAME POSR 3 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: max warning limit
CL_FRM "MinWarning" SHOWNAME POSR 4 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: min warning limit
CL_FRM "MinAlarm" SHOWNAME POSR 5 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: min alarm limit
CL_FRM "Invalid" SHOWNAME POSR 7 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: measuring is invalid
CL_PRT extern"C"BOOL FB_CALL_CONV AN_LIM_7(const PTR_WORD,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_BOOL);
//
// Elementary Function Block:  AN_SCAL
//
//                      ____________________
//                     |                    |
//                     |      AN_SCAL       |
//                     |                    |
//             UINT ---| RawValue ScalValue |--- UINT            
//             BOOL ---| Card_Healty           |                    
//             UINT ---| In_max             |                    
//                     |____________________|
//
// AN_SCAL
//
CL_EFB "AN_SCAL" "Analog" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 6 12 "08/01/18 11:00:21" TEXT: Analog scaling
CL_FRM "RawValue" SHOWNAME POSL 2 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: analog raw value
CL_FRM "Card_Healty" SHOWNAME POSL 3 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Card healty information. 1=OK
CL_FRM "In_max" SHOWNAME POSL 4 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: Max raw value
CL_FRM "ScalValue" SHOWNAME POSR 2 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE UINT TEXT: scaling value
CL_PRT extern"C"BOOL FB_CALL_CONV AN_SCAL(const PTR_UINT,
...PRT const PTR_BOOL,
...PRT const PTR_UINT,
...PRT PTR_UINT);
//
// Elementary Function Block:  AN_SCHED
//
//                      ____________________
//                     |                    |
//                     |      AN_SCHED      |
//                     |                    |
//              INT ---| SchReg    Sch_Mea1 |--- BOOL            
//                     |           Sch_Mea2 |--- BOOL            
//                     |           Sch_Mea3 |--- BOOL            
//                     |           Sch_Mea4 |--- BOOL            
//                     |           Sch_Mea5 |--- BOOL            
//                     |           Sch_Mea6 |--- BOOL            
//                     |           Sch_Mea7 |--- BOOL            
//                     |           Sch_Mea8 |--- BOOL            
//                     |____________________|
//
// AN_SCHED
//
CL_EFB "AN_SCHED" "Analog" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 11 10 "08/01/18 11:22:54" TEXT: Schedule the execution of maximum 8 analog processing function blocks
CL_FRM "SchReg" SHOWNAME POSL 2 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE INT TEXT: Scheduling control register
CL_FRM "Istate" SHOWNAME POSR 1 FP_IO_OUTPUT FP_OUTP_INTERN_STATE FP_LOC_HIDDEN INTSTATE VAL: 2 TEXT: Internal State
CL_FRM "Sch_Mea1" SHOWNAME POSR 2 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Scheduled EN1 for measuring
CL_FRM "Sch_Mea2" SHOWNAME POSR 3 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Scheduled EN2 for measuring
CL_FRM "Sch_Mea3" SHOWNAME POSR 4 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Scheduled EN3 for measuring
CL_FRM "Sch_Mea4" SHOWNAME POSR 5 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Scheduled EN4 for measuring
CL_FRM "Sch_Mea5" SHOWNAME POSR 6 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Scheduled EN5 for measuring
CL_FRM "Sch_Mea6" SHOWNAME POSR 7 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Scheduled EN6 for measuring
CL_FRM "Sch_Mea7" SHOWNAME POSR 8 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Scheduled EN7 for measuring
CL_FRM "Sch_Mea8" SHOWNAME POSR 9 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Scheduled EN8 for measuring
CL_PRT extern"C"BOOL FB_CALL_CONV AN_SCHED(const PTR_INT,
...PRT PTR_Istat_AN_SCHED,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_BOOL);
//
// Elementary Function Block:  ARCHFAIL
//
//                      ____________________
//                     |                    |
//                     |      ARCHFAIL      |
//                     |                    |
//  AUX_1_ARCH_TABL ---| ArchTbl----ArchTbl |--- AUX_1_ARCH_TABL
//                     |____________________|
//
// ARCHFAIL
//
CL_EFB "ARCHFAIL" "Archive" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 4 9 "08/01/18 11:00:21" TEXT: Incrementing failure counters in the archive table.
CL_FRM "ArchTbl" SHOWNAME POSR 2 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE AUX_1_ARCH_TABL TEXT: Archive table
CL_PRT extern"C"BOOL FB_CALL_CONV ARCHFAIL(PTR_AUX_1_ARCH_TABL);
//
// Elementary Function Block:  ARCHGOPR
//
//                      ____________________
//                     |                    |
//                     |      ARCHGOPR      |
//                     |                    |
//   GV_ARCH_TABLES ---| ArchTbl----ArchTbl |--- GV_ARCH_TABLES
//   GV_ARCH_EVENTS ---| Events1----Events1 |--- GV_ARCH_EVENTS
//   GV_ARCH_EVENTS ---| Events2----Events2 |--- GV_ARCH_EVENTS
//                     |                    |                    
//             WORD ---| ArchPt1----ArchPt1 |--- WORD
//             WORD ---| ArchPt2----ArchPt2 |--- WORD
//        TOD_CLOCK ---| Clock              |                    
//                     |____________________|
//
// ARCHGOPR
//
CL_EFB "ARCHGOPR" "Archive" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 10 10 "08/01/18 11:00:21" TEXT: Fixing the operator's time of the gate valves.
CL_FRM "Clock" SHOWNAME POSL 8 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE TOD_CLOCK TEXT: TOD clock
CL_FRM "ArchTbl" SHOWNAME POSR 2 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE GV_ARCH_TABLES TEXT: Archive table
CL_FRM "Events1" SHOWNAME POSR 3 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE GV_ARCH_EVENTS TEXT: Event block
CL_FRM "Events2" SHOWNAME POSR 4 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE GV_ARCH_EVENTS TEXT: Event block
CL_FRM "ArchPt1" SHOWNAME POSR 6 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE WORD TEXT: Pointer for setting oper's time
CL_FRM "ArchPt2" SHOWNAME POSR 7 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE WORD TEXT: Pointer for setting oper's time
CL_PRT extern"C"BOOL FB_CALL_CONV ARCHGOPR(const PTR_TOD_CLOCK,
...PRT PTR_GV_ARCH_TABLES,
...PRT PTR_GV_ARCH_EVENTS,
...PRT PTR_GV_ARCH_EVENTS,
...PRT PTR_WORD,
...PRT PTR_WORD);
//
// Elementary Function Block:  ARCHGTVL
//
//                      ____________________
//                     |                    |
//                     |      ARCHGTVL      |
//                     |                    |
//        GVARCHTBL ---| ArchTbl----ArchTbl |--- GVARCHTBL
//             WORD ---| GVStat2            |                    
//        TOD_CLOCK ---| TODCLOCK           |                    
//                     |____________________|
//
// ARCHGTVL
//
CL_EFB "ARCHGTVL" "Archive" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 6 9 "08/01/18 11:22:54" TEXT: A full working test example.
CL_FRM "GVStat2" SHOWNAME POSL 3 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE WORD TEXT: Gate Valve 2.status word 
CL_FRM "TODCLOCK" SHOWNAME POSL 4 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE TOD_CLOCK TEXT: System time
CL_FRM "Istate" SHOWNAME POSR 1 FP_IO_OUTPUT FP_OUTP_INTERN_STATE FP_LOC_HIDDEN INTSTATE VAL: 5 TEXT: Internal State
CL_FRM "ArchTbl" SHOWNAME POSR 2 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE GVARCHTBL TEXT: Archive table
CL_PRT extern"C"BOOL FB_CALL_CONV ARCHGTVL(const PTR_WORD,
...PRT const PTR_TOD_CLOCK,
...PRT PTR_Istat_ARCHGTVL,
...PRT PTR_GVARCHTBL);
//
// Elementary Function Block:  ARCHNWDY
//
//                      ____________________
//                     |                    |
//                     |      ARCHNWDY      |
//                     |                    |
//      ARCH_TABLES ---| ArchTbl----ArchTbl |--- ARCH_TABLES
//             BOOL ---| NewDay             |                    
//                     |____________________|
//
// ARCHNWDY
//
CL_EFB "ARCHNWDY" "Archive" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 5 9 "08/01/18 11:00:21" TEXT: Refreshing archive information at the beginning of a new day.
CL_FRM "NewDay" SHOWNAME POSL 3 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: New day
CL_FRM "ArchTbl" SHOWNAME POSR 2 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE ARCH_TABLES TEXT: Archive table
CL_PRT extern"C"BOOL FB_CALL_CONV ARCHNWDY(const PTR_BOOL,
...PRT PTR_ARCH_TABLES);
//
// Elementary Function Block:  ARCHNWMT
//
//                      ____________________
//                     |                    |
//                     |      ARCHNWMT      |
//                     |                    |
//      ARCH_TABLES ---| ArchTbl----ArchTbl |--- ARCH_TABLES
//             BOOL ---| NewMonth           |                    
//                     |____________________|
//
// ARCHNWMT
//
CL_EFB "ARCHNWMT" "Archive" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 5 9 "08/01/18 11:00:21" TEXT: Refreshing archive information at the beginning of a new month.
CL_FRM "NewMonth" SHOWNAME POSL 3 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: New month
CL_FRM "ArchTbl" SHOWNAME POSR 2 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE ARCH_TABLES TEXT: Archive table
CL_PRT extern"C"BOOL FB_CALL_CONV ARCHNWMT(const PTR_BOOL,
...PRT PTR_ARCH_TABLES);
//
// Elementary Function Block:  ARCHOPRT
//
//                      ____________________
//                     |                    |
//                     |      ARCHOPRT      |
//                     |                    |
//      ARCH_TABLES ---| ArchTbl----ArchTbl |--- ARCH_TABLES
//      ARCH_EVENTS ---| Events1----Events1 |--- ARCH_EVENTS
//      ARCH_EVENTS ---| Events2----Events2 |--- ARCH_EVENTS
//                     |                    |                    
//             WORD ---| ArchPt1----ArchPt1 |--- WORD
//             WORD ---| ArchPt2----ArchPt2 |--- WORD
//        TOD_CLOCK ---| Clock              |                    
//                     |____________________|
//
// ARCHOPRT
//
CL_EFB "ARCHOPRT" "Archive" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 10 10 "08/01/18 11:00:21" TEXT: Fixing the operator's time of the techn. unit.
CL_FRM "Clock" SHOWNAME POSL 8 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE TOD_CLOCK TEXT: TOD clock
CL_FRM "ArchTbl" SHOWNAME POSR 2 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE ARCH_TABLES TEXT: Archive table
CL_FRM "Events1" SHOWNAME POSR 3 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE ARCH_EVENTS TEXT: Event block
CL_FRM "Events2" SHOWNAME POSR 4 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE ARCH_EVENTS TEXT: Event block
CL_FRM "ArchPt1" SHOWNAME POSR 6 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE WORD TEXT: Pointer for setting remont time
CL_FRM "ArchPt2" SHOWNAME POSR 7 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE WORD TEXT: Pointer for setting remont time
CL_PRT extern"C"BOOL FB_CALL_CONV ARCHOPRT(const PTR_TOD_CLOCK,
...PRT PTR_ARCH_TABLES,
...PRT PTR_ARCH_EVENTS,
...PRT PTR_ARCH_EVENTS,
...PRT PTR_WORD,
...PRT PTR_WORD);
//
// Elementary Function Block:  ARCHREMT
//
//                      ____________________
//                     |                    |
//                     |      ARCHREMT      |
//                     |                    |
//      ARCH_TABLES ---| ArchTbl----ArchTbl |--- ARCH_TABLES
//      ARCH_EVENTS ---| Events1----Events1 |--- ARCH_EVENTS
//      ARCH_EVENTS ---| Events2----Events2 |--- ARCH_EVENTS
//                     |                    |                    
//             WORD ---| ArchPt1----ArchPt1 |--- WORD
//             WORD ---| ArchPt2----ArchPt2 |--- WORD
//        TOD_CLOCK ---| Clock              |                    
//                     |____________________|
//
// ARCHREMT
//
CL_EFB "ARCHREMT" "Archive" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 10 10 "08/01/18 11:00:21" TEXT: Fixing the remont time of the techn. unit.
CL_FRM "Clock" SHOWNAME POSL 8 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE TOD_CLOCK TEXT: TOD clock
CL_FRM "ArchTbl" SHOWNAME POSR 2 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE ARCH_TABLES TEXT: Archive table
CL_FRM "Events1" SHOWNAME POSR 3 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE ARCH_EVENTS TEXT: Event block
CL_FRM "Events2" SHOWNAME POSR 4 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE ARCH_EVENTS TEXT: Event block
CL_FRM "ArchPt1" SHOWNAME POSR 6 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE WORD TEXT: Pointer for setting remont time
CL_FRM "ArchPt2" SHOWNAME POSR 7 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE WORD TEXT: Pointer for setting remont time
CL_PRT extern"C"BOOL FB_CALL_CONV ARCHREMT(const PTR_TOD_CLOCK,
...PRT PTR_ARCH_TABLES,
...PRT PTR_ARCH_EVENTS,
...PRT PTR_ARCH_EVENTS,
...PRT PTR_WORD,
...PRT PTR_WORD);
//
// Elementary Function Block:  ARCHSTAR
//
//                      ____________________
//                     |                    |
//                     |      ARCHSTAR      |
//                     |                    |
//  AUX_1_ARCH_TABL ---| ArchTbl----ArchTbl |--- AUX_1_ARCH_TABL
//             BOOL ---| HotStart           |                    
//                     |____________________|
//
// ARCHSTAR
//
CL_EFB "ARCHSTAR" "Archive" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 5 9 "08/01/18 11:00:21" TEXT: Incrementing hot/cold start counters in the archive table.
CL_FRM "HotStart" SHOWNAME POSL 3 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Hot/Cold start selector
CL_FRM "ArchTbl" SHOWNAME POSR 2 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE AUX_1_ARCH_TABL TEXT: Archive table
CL_PRT extern"C"BOOL FB_CALL_CONV ARCHSTAR(const PTR_BOOL,
...PRT PTR_AUX_1_ARCH_TABL);
//
// Elementary Function Block:  ARCHSTPT
//
//                      ____________________
//                     |                    |
//                     |      ARCHSTPT      |
//                     |                    |
//  AUX_1_ARCH_TABL ---| ArchTbl----ArchTbl |--- AUX_1_ARCH_TABL
//        TOD_CLOCK ---| Clock              |                    
//                     |____________________|
//
// ARCHSTPT
//
CL_EFB "ARCHSTPT" "Archive" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 5 9 "08/01/18 11:00:21" TEXT: Fixing the moment of the agregate stop in the archive table.
CL_FRM "Clock" SHOWNAME POSL 3 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE TOD_CLOCK TEXT: TOD clock
CL_FRM "ArchTbl" SHOWNAME POSR 2 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE AUX_1_ARCH_TABL TEXT: Archive table
CL_PRT extern"C"BOOL FB_CALL_CONV ARCHSTPT(const PTR_TOD_CLOCK,
...PRT PTR_AUX_1_ARCH_TABL);
//
// Elementary Function Block:  ARCHSTRT
//
//                      ____________________
//                     |                    |
//                     |      ARCHSTRT      |
//                     |                    |
//  AUX_1_ARCH_TABL ---| ArchTbl----ArchTbl |--- AUX_1_ARCH_TABL
//        TOD_CLOCK ---| Clock              |                    
//                     |____________________|
//
// ARCHSTRT
//
CL_EFB "ARCHSTRT" "Archive" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 5 9 "08/01/18 11:00:21" TEXT: Fixing the moment of the agregate start in the archive table.
CL_FRM "Clock" SHOWNAME POSL 3 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE TOD_CLOCK TEXT: TOD clock
CL_FRM "ArchTbl" SHOWNAME POSR 2 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE AUX_1_ARCH_TABL TEXT: Archive table
CL_PRT extern"C"BOOL FB_CALL_CONV ARCHSTRT(const PTR_TOD_CLOCK,
...PRT PTR_AUX_1_ARCH_TABL);
//
// Elementary Function Block:  ARCHWHLS
//
//                      ____________________
//                     |                    |
//                     |      ARCHWHLS      |
//                     |                    |
//  AUX_1_ARCH_TABL ---| ArchTbl----ArchTbl |--- AUX_1_ARCH_TABL
//             BOOL ---| Clk                |                    
//             BOOL ---| Reset              |                    
//                     |____________________|
//
// ARCHWHLS
//
CL_EFB "ARCHWHLS" "Archive" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 6 9 "08/01/18 11:00:21" TEXT: Counting workhours since the last start.
CL_FRM "Clk" SHOWNAME POSL 3 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Clock signal to count
CL_FRM "Reset" SHOWNAME POSL 4 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Reset signal
CL_FRM "ArchTbl" SHOWNAME POSR 2 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE AUX_1_ARCH_TABL TEXT: Archive table
CL_PRT extern"C"BOOL FB_CALL_CONV ARCHWHLS(const PTR_BOOL,
...PRT const PTR_BOOL,
...PRT PTR_AUX_1_ARCH_TABL);
//
// Elementary Function Block:  ARCHWRKH
//
//                      ____________________
//                     |                    |
//                     |      ARCHWRKH      |
//                     |                    |
//  AUX_1_ARCH_TABL ---| ArchTbl----ArchTbl |--- AUX_1_ARCH_TABL
//                     |____________________|
//
// ARCHWRKH
//
CL_EFB "ARCHWRKH" "Archive" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 4 9 "08/01/18 11:00:21" TEXT: Counting workhours in the archive table.
CL_FRM "ArchTbl" SHOWNAME POSR 2 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE AUX_1_ARCH_TABL TEXT: Archive table
CL_PRT extern"C"BOOL FB_CALL_CONV ARCHWRKH(PTR_AUX_1_ARCH_TABL);
//
// Elementary Function Block:  ARCHWRKM
//
//                      ____________________
//                     |                    |
//                     |      ARCHWRKM      |
//                     |                    |
//  AUX_1_ARCH_TABL ---| ArchTbl----ArchTbl |--- AUX_1_ARCH_TABL
//                     |____________________|
//
// ARCHWRKM
//
CL_EFB "ARCHWRKM" "Archive" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 4 9 "08/01/18 11:00:21" TEXT: Counting workminutes in the archive table.
CL_FRM "ArchTbl" SHOWNAME POSR 2 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE AUX_1_ARCH_TABL TEXT: Archive table
CL_PRT extern"C"BOOL FB_CALL_CONV ARCHWRKM(PTR_AUX_1_ARCH_TABL);
//
// Elementary Function Block:  BIN_DEC
//
//                      ____________________
//                     |                    |
//                     |      BIN_DEC       |
//                     |                    |
//             BOOL ---| In             Num |--- UINT            
//                   : |                    |                    
//             BOOL ---| In                 |                    
//                     |____________________|
//
// BIN_DEC
//
CL_EFB "BIN_DEC" "General" ANYPIN_NO FBTK_EFB_EXT HEIGHT/WIDTH: 5 5 "08/01/18 11:00:21" TEXT: Binary to Decimal converter
CL_FRM "nin" SHOWNAME POSL 1 FP_IO_INPUT FP_INP_IMMEDIATE_NIN FP_LOC_HIDDEN INT VAL: 2 TEXT: extensible input count
CL_FRM "Num" SHOWNAME POSR 2 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE UINT TEXT: decimal number
CL_FRM "In1" SHOWNAME POSL 2 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: extensible inputs
CL_FRM "In2" SHOWNAME POSL 3 FP_IO_INPUT FP_INP_EXTENSIBLE FP_LOC_OUTSIDE BOOL VAL: 14 TEXT: extensible inputs
CL_PRT extern"C"BOOL FB_CALL_CONV BIN_DEC(INT,
...PRT PTR_UINT,
...PRT ...);
//
// Elementary Function Block:  BIT64_WD
//
//                      ____________________
//                     |                    |
//                     |      BIT64_WD      |
//                     |                    |
//  AUX_1_EVNT_MESS ---| BOOL64       WORD4 |--- AUX_1_EVNT_REGS 
//                     |                    |                    
//                     |              Error |--- BOOL            
//                     |               Diag |--- WORD            
//                     |____________________|
//
// BIT64_WD
//
CL_EFB "BIT64_WD" "General" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 7 9 "08/01/18 11:00:21" TEXT: Copying a 64 element BOOL table to 4 words.
CL_FRM "BOOL64" SHOWNAME POSL 2 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE AUX_1_EVNT_MESS TEXT: 64 BOOL-s to be converted
CL_FRM "WORD4" SHOWNAME POSR 2 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE AUX_1_EVNT_REGS TEXT: Destination block of WORD-s
CL_FRM "Error" SHOWNAME POSR 4 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Error flag
CL_FRM "Diag" SHOWNAME POSR 5 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE WORD TEXT: Diagnostics
CL_PRT extern"C"BOOL FB_CALL_CONV BIT64_WD(const PTR_AUX_1_EVNT_MESS,
...PRT PTR_AUX_1_EVNT_REGS,
...PRT PTR_BOOL,
...PRT PTR_WORD);
//
// Elementary Function Block:  BOOL_ADD
//
//                      ____________________
//                     |                    |
//                     |      BOOL_ADD      |
//                     |                    |
//                     |                Num |--- WORD            
//             BOOL ---| In                 |                    
//                   : |                    |                    
//             BOOL ---| In                 |                    
//                     |____________________|
//
// BOOL_ADD
//
CL_EFB "BOOL_ADD" "General" ANYPIN_NO FBTK_EFB_EXT HEIGHT/WIDTH: 6 6 "08/01/18 11:00:21" TEXT: Add BOOL input
CL_FRM "nin" SHOWNAME POSL 1 FP_IO_INPUT FP_INP_IMMEDIATE_NIN FP_LOC_HIDDEN INT VAL: 2 TEXT: extensible input count
CL_FRM "Num" SHOWNAME POSR 2 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE WORD TEXT: Number of TRUE BOOL
CL_FRM "In1" SHOWNAME POSL 3 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: extensible inputs
CL_FRM "In2" SHOWNAME POSL 4 FP_IO_INPUT FP_INP_EXTENSIBLE FP_LOC_OUTSIDE BOOL VAL: 28 TEXT: extensible inputs
CL_PRT extern"C"BOOL FB_CALL_CONV BOOL_ADD(INT,
...PRT PTR_WORD,
...PRT ...);
//
// Elementary Function Block:  CHDET
//
//                      ____________________
//                     |                    |
//                     |       CHDET        |
//                     |                    |
//             WORD ---| ChDetW------ChDetW |--- WORD
//             UINT ---| BitNo              |                    
//                     |                    |                    
//              CHD ---| DirAddr            |                    
//             UINT ---| Add_From           |                    
//             UINT ---| Add_To             |                    
//                     |____________________|
//
// CHDET
//
CL_EFB "CHDET" "General" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 9 9 "08/01/18 11:22:54" TEXT: Change detection in the table
CL_FRM "BitNo" SHOWNAME POSL 3 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: Bit number in the chdet word
CL_FRM "DirAddr" SHOWNAME POSL 5 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE CHD TEXT: Direct start address of change detected table
CL_FRM "Add_From" SHOWNAME POSL 6 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: Change detection dir addr
CL_FRM "Add_To" SHOWNAME POSL 7 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: End address of change detection in the 100 table
CL_FRM "Istate" SHOWNAME POSR 1 FP_IO_OUTPUT FP_OUTP_INTERN_STATE FP_LOC_HIDDEN INTSTATE VAL: 200 TEXT: Internal State
CL_FRM "ChDetW" SHOWNAME POSR 2 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE WORD TEXT: Word for change detection
CL_PRT extern"C"BOOL FB_CALL_CONV CHDET(const PTR_UINT,
...PRT const PTR_CHD,
...PRT const PTR_UINT,
...PRT const PTR_UINT,
...PRT PTR_Istat_CHDET,
...PRT PTR_WORD);
//
// Elementary Function Block:  CHKSUM
//
//                      ____________________
//                     |                    |
//                     |       CHKSUM       |
//                     |                    |
//              BLK ---| Table          Err |--- BOOL            
//             UINT ---| Offset    WrngChkS |--- BOOL            
//             UINT ---| Length             |                    
//             WORD ---| ChkSum     ChkSOut |--- WORD            
//                     |____________________|
//
// CHKSUM
//
CL_EFB "CHKSUM" "General" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 7 10 "08/01/18 11:00:21" TEXT: Calculating / checking checksum
CL_FRM "Table" SHOWNAME POSL 2 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BLK TEXT: Direct start address of the table
CL_FRM "Offset" SHOWNAME POSL 3 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: Table length
CL_FRM "Length" SHOWNAME POSL 4 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: Table length
CL_FRM "ChkSum" SHOWNAME POSL 5 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE WORD TEXT: The received check sum
CL_FRM "Err" SHOWNAME POSR 2 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Error output
CL_FRM "WrngChkS" SHOWNAME POSR 3 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Wrong checksum
CL_FRM "ChkSOut" SHOWNAME POSR 5 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE WORD TEXT: The generated checksum from the block
CL_PRT extern"C"BOOL FB_CALL_CONV CHKSUM(const PTR_BLK,
...PRT const PTR_UINT,
...PRT const PTR_UINT,
...PRT const PTR_WORD,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_WORD);
//
// Elementary Function Block:  DEMUX2
//
//                      ____________________
//                     |                    |
//                     |       DEMUX2       |
//                     |                    |
//             BOOL ---| G             Out0 |--- ANY             
//              ANY ---| In            Out1 |--- ANY             
//                     |____________________|
//
// DEMUX2
//
CL_EFB "DEMUX2" "General" ANYPIN_ANY_PIN FBTK_EFB HEIGHT/WIDTH: 5 5 "08/01/18 11:00:21" TEXT: Input signal is copyed to Out1 or Out0 depending upon the
...TXT             value of the G signal.
CL_FRM "G" SHOWNAME POSL 2 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT:
CL_FRM "In" SHOWNAME POSL 3 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE ANY TEXT:
CL_FRM "sizein" SHOWNAME POSL 1 FP_IO_INPUT FP_INP_IMMEDIATE_SIZE FP_LOC_HIDDEN INT TEXT: size of ANY data
CL_FRM "Out0" SHOWNAME POSR 2 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE ANY TEXT:
CL_FRM "Out1" SHOWNAME POSR 3 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE ANY TEXT:
CL_PRT extern"C"BOOL FB_CALL_CONV DEMUX2(const PTR_BOOL,
...PRT const PTR_ANY,
...PRT INT,
...PRT PTR_ANY,
...PRT PTR_ANY);
//
// Elementary Function Block:  EVENT1
//
//                      ____________________
//                     |                    |
//                     |       EVENT1       |
//                     |                    |
//     COMMUN_BLOCK ---| CommBlk----CommBlk |--- COMMUN_BLOCK
//       ST_TBLS_T1 ---| StTbl--------StTbl |--- ST_TBLS_T1
//        DS_TBLS_T ---| ChDsTb       InTbl |--- IN_TBLS_T       
//                     |                    |                    
//             BOOL ---| TM_Mode      Error |--- BOOL            
//             BOOL ---| NoStTbCl ActEvents |--- BOOL            
//             BOOL ---> DtbRead EvBuffFull |--- BOOL            
//             BOOL ---> Restart  LostEvent |--- BOOL            
//                     |              Diagn |--- DIAG_BLOCK      
//                     |____________________|
//
// EVENT1
//
CL_EFB "EVENT1" "General" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 12 11 "08/01/18 11:22:54" TEXT: Creating event messages from signal changes in state tables.
...TXT             Sending this messages is accomplished through the secondary
...TXT             event buffer.
CL_FRM "ChDsTb" SHOWNAME POSL 4 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE DS_TBLS_T TEXT: Gen.change descr.table
CL_FRM "TM_Mode" SHOWNAME POSL 6 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: TM type processing
CL_FRM "NoStTbCl" SHOWNAME POSL 7 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: No state table clear
CL_FRM "DtbRead" SHOWNAME POSL 8 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL FP_TRG_RISING_EDGE TEXT: Database read
CL_FRM "Restart" SHOWNAME POSL 9 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL FP_TRG_RISING_EDGE TEXT: System restart
CL_FRM "Istate" SHOWNAME POSR 1 FP_IO_OUTPUT FP_OUTP_INTERN_STATE FP_LOC_HIDDEN INTSTATE VAL: 5130 TEXT: Internal State
CL_FRM "CommBlk" SHOWNAME POSR 2 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE COMMUN_BLOCK TEXT: Communication block
CL_FRM "StTbl" SHOWNAME POSR 3 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE ST_TBLS_T1 TEXT: Gen. state table
CL_FRM "InTbl" SHOWNAME POSR 4 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE IN_TBLS_T TEXT: Gen. init. table
CL_FRM "Error" SHOWNAME POSR 6 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Error flag
CL_FRM "ActEvents" SHOWNAME POSR 7 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Active events exist
CL_FRM "EvBuffFull" SHOWNAME POSR 8 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: The event buffer is full
CL_FRM "LostEvent" SHOWNAME POSR 9 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Event loosing occured
CL_FRM "Diagn" SHOWNAME POSR 10 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE DIAG_BLOCK TEXT: for diagnostic purposes
CL_PRT extern"C"BOOL FB_CALL_CONV EVENT1(const PTR_DS_TBLS_T,
...PRT const PTR_BOOL,
...PRT const PTR_BOOL,
...PRT const PTR_BOOL,
...PRT const PTR_BOOL,
...PRT PTR_Istat_EVENT1,
...PRT PTR_COMMUN_BLOCK,
...PRT PTR_ST_TBLS_T1,
...PRT PTR_IN_TBLS_T,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_DIAG_BLOCK);
//
// Elementary Function Block:  EVENT
//
//                      ____________________
//                     |                    |
//                     |       EVENT        |
//                     |                    |
//     COMMUN_BLOCK ---| CommBlk----CommBlk |--- COMMUN_BLOCK
//        ST_TBLS_T ---| StTbl--------StTbl |--- ST_TBLS_T
//     GV_ST_TBLS_T ---| GvStTbl----GvStTbl |--- GV_ST_TBLS_T
//     AN_ST_TBLS_T ---| AnStTbl----AnStTbl |--- AN_ST_TBLS_T
//                     |              InTbl |--- IN_TBLS_T       
//     GV_DS_TBLS_T ---| GvStDsTb   GvInTbl |--- GV_IN_TBLS_T    
//     AN_DS_TBLS_T ---| AnStDsTb   AnInTbl |--- AN_IN_TBLS_T    
//        DS_TBLS_T ---| ChDsTb             |                    
//     GV_DS_TBLS_T ---| GvChDsTb           |                    
//     AN_DS_TBLS_T ---| AnChDsTb           |                    
//             BOOL ---| TM_Mode      Error |--- BOOL            
//             BOOL ---| NoStTbCl ActEvents |--- BOOL            
//             BOOL ---> DtbRead EvBuffFull |--- BOOL            
//             BOOL ---> Restart  LostEvent |--- BOOL            
//                     |              Diagn |--- DIAG_BLOCK      
//                     |____________________|
//
// EVENT
//
CL_EFB "EVENT" "General" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 18 11 "08/01/18 11:22:54" TEXT: Creating event messages from signal changes in state tables.
CL_FRM "GvStDsTb" SHOWNAME POSL 7 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE GV_DS_TBLS_T TEXT: Gate valve state descr.table
CL_FRM "AnStDsTb" SHOWNAME POSL 8 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE AN_DS_TBLS_T TEXT: Ana.state descr.table
CL_FRM "ChDsTb" SHOWNAME POSL 9 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE DS_TBLS_T TEXT: Gen.change descr.table
CL_FRM "GvChDsTb" SHOWNAME POSL 10 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE GV_DS_TBLS_T TEXT: Gate valve change descr.table
CL_FRM "AnChDsTb" SHOWNAME POSL 11 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE AN_DS_TBLS_T TEXT: Ana.change descr.table
CL_FRM "TM_Mode" SHOWNAME POSL 12 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: TM type processing
CL_FRM "NoStTbCl" SHOWNAME POSL 13 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: No state table clear
CL_FRM "DtbRead" SHOWNAME POSL 14 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL FP_TRG_RISING_EDGE TEXT: Database read
CL_FRM "Restart" SHOWNAME POSL 15 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL FP_TRG_RISING_EDGE TEXT: System restart
CL_FRM "Istate" SHOWNAME POSR 1 FP_IO_OUTPUT FP_OUTP_INTERN_STATE FP_LOC_HIDDEN INTSTATE VAL: 5898 TEXT: Internal State
CL_FRM "CommBlk" SHOWNAME POSR 2 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE COMMUN_BLOCK TEXT: Communication block
CL_FRM "StTbl" SHOWNAME POSR 3 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE ST_TBLS_T TEXT: Gen. state table
CL_FRM "GvStTbl" SHOWNAME POSR 4 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE GV_ST_TBLS_T TEXT: Gate valve state table
CL_FRM "AnStTbl" SHOWNAME POSR 5 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE AN_ST_TBLS_T TEXT: Analog state table
CL_FRM "InTbl" SHOWNAME POSR 6 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE IN_TBLS_T TEXT: Gen. init. table
CL_FRM "GvInTbl" SHOWNAME POSR 7 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE GV_IN_TBLS_T TEXT: Gate valve init. table
CL_FRM "AnInTbl" SHOWNAME POSR 8 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE AN_IN_TBLS_T TEXT: Analog init. table
CL_FRM "Error" SHOWNAME POSR 12 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Error flag
CL_FRM "ActEvents" SHOWNAME POSR 13 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Active events exist
CL_FRM "EvBuffFull" SHOWNAME POSR 14 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: The event buffer is full
CL_FRM "LostEvent" SHOWNAME POSR 15 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Event loosing occured
CL_FRM "Diagn" SHOWNAME POSR 16 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE DIAG_BLOCK TEXT: for diagnostic purposes
CL_PRT extern"C"BOOL FB_CALL_CONV EVENT(const PTR_GV_DS_TBLS_T,
...PRT const PTR_AN_DS_TBLS_T,
...PRT const PTR_DS_TBLS_T,
...PRT const PTR_GV_DS_TBLS_T,
...PRT const PTR_AN_DS_TBLS_T,
...PRT const PTR_BOOL,
...PRT const PTR_BOOL,
...PRT const PTR_BOOL,
...PRT const PTR_BOOL,
...PRT PTR_Istat_EVENT,
...PRT PTR_COMMUN_BLOCK,
...PRT PTR_ST_TBLS_T,
...PRT PTR_GV_ST_TBLS_T,
...PRT PTR_AN_ST_TBLS_T,
...PRT PTR_IN_TBLS_T,
...PRT PTR_GV_IN_TBLS_T,
...PRT PTR_AN_IN_TBLS_T,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_DIAG_BLOCK);
//
// Elementary Function Block:  MBPCable
//
//                      ____________________
//                     |                    |
//                     |      MBPCable      |
//                     |                    |
//             WORD ---| ErrCount  ACableOK |--- BOOL            
//                     |           BCableOK |--- BOOL            
//                     |____________________|
//
// MBPCable
//
CL_EFB "MBPCable" "General" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 5 11 "08/01/18 11:22:54" TEXT: Checking MB Plus Cable healthy.
CL_FRM "ErrCount" SHOWNAME POSL 2 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE WORD TEXT: Cable healthy counters
CL_FRM "Istate" SHOWNAME POSR 1 FP_IO_OUTPUT FP_OUTP_INTERN_STATE FP_LOC_HIDDEN INTSTATE VAL: 4 TEXT: Internal State
CL_FRM "ACableOK" SHOWNAME POSR 2 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Cable A OK
CL_FRM "BCableOK" SHOWNAME POSR 3 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Cable B OK
CL_PRT extern"C"BOOL FB_CALL_CONV MBPCable(const PTR_WORD,
...PRT PTR_Istat_MBPCable,
...PRT PTR_BOOL,
...PRT PTR_BOOL);
//
// Elementary Function Block:  PATTCNTR
//
//                      ____________________
//                     |                    |
//                     |      PATTCNTR      |
//                     |                    |
//             WORD ---| Mask           Out |--- WORD            
//             WORD ---| Limit        Above |--- BOOL            
//             WORD ---| In           Equal |--- BOOL            
//                   : |              Below |--- BOOL            
//             WORD ---| In                 |                    
//                     |____________________|
//
// PATTCNTR
//
CL_EFB "PATTCNTR" "General" ANYPIN_NO FBTK_EFB_EXT HEIGHT/WIDTH: 7 7 "08/01/18 11:00:21" TEXT: Adding # of inputs that are matching given criteria (ext.inputs)
...TXT  The sum of all inputs is calculated and copied to the output OUT
...TXT  Note: No error checks are made on overflow!
CL_FRM "Mask" SHOWNAME POSL 2 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE WORD TEXT: mask value
CL_FRM "Limit" SHOWNAME POSL 3 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE WORD TEXT: limit value
CL_FRM "nin" SHOWNAME POSL 1 FP_IO_INPUT FP_INP_IMMEDIATE_NIN FP_LOC_HIDDEN INT VAL: 2 TEXT: extensible input count
CL_FRM "Out" SHOWNAME POSR 2 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE WORD TEXT: computed output
CL_FRM "Above" SHOWNAME POSR 3 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: the sum is above the limit
CL_FRM "Equal" SHOWNAME POSR 4 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: the sum is equal the limit
CL_FRM "Below" SHOWNAME POSR 5 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: the sum is below the limit
CL_FRM "In1" SHOWNAME POSL 4 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE WORD TEXT: extensible inputs
CL_FRM "In2" SHOWNAME POSL 5 FP_IO_INPUT FP_INP_EXTENSIBLE FP_LOC_OUTSIDE WORD VAL: 28 TEXT: extensible inputs
CL_PRT extern"C"BOOL FB_CALL_CONV PATTCNTR(const PTR_WORD,
...PRT const PTR_WORD,
...PRT INT,
...PRT PTR_WORD,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT ...);
//
// Elementary Function Block:  SAMPLER
//
//                      ____________________
//                     |                    |
//                     |      SAMPLER       |
//                     |                    |
//              ANY ---| In             Out |--- ANY             
//             BOOL ---> Clk                |                    
//                     |____________________|
//
// SAMPLER
//
CL_EFB "SAMPLER" "General" ANYPIN_ANY_PIN FBTK_EFB HEIGHT/WIDTH: 5 6 "08/01/18 11:22:54" TEXT: Sampling input at the rising edge of the Clk signal.
CL_FRM "In" SHOWNAME POSL 2 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE ANY TEXT:
CL_FRM "Clk" SHOWNAME POSL 3 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL FP_TRG_RISING_EDGE TEXT:
CL_FRM "sizein" SHOWNAME POSL 1 FP_IO_INPUT FP_INP_IMMEDIATE_SIZE FP_LOC_HIDDEN INT TEXT: size of ANY data
CL_FRM "Istate" SHOWNAME POSR 1 FP_IO_OUTPUT FP_OUTP_INTERN_STATE FP_LOC_HIDDEN INTSTATE VAL: 1 TEXT: Internal State
CL_FRM "Out" SHOWNAME POSR 2 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE ANY TEXT:
CL_PRT extern"C"BOOL FB_CALL_CONV SAMPLER(const PTR_ANY,
...PRT const PTR_BOOL,
...PRT INT,
...PRT PTR_Istat_SAMPLER,
...PRT PTR_ANY);
//
// Elementary Function Block:  SCALER
//
//                      ____________________
//                     |                    |
//                     |       SCALER       |
//                     |                    |
//          ANY_INT ---| RawValue ScalValue |--- ANY_INT         
//                     |              Error |--- BOOL            
//          ANY_INT ---| In_max             |                    
//          ANY_INT ---| In_min             |                    
//          ANY_INT ---| Out_max            |                    
//          ANY_INT ---| Out_min            |                    
//                     |____________________|
//
// SCALER
//
CL_EFB "SCALER" "General" ANYPIN_FRONTEND FBTK_EFB HEIGHT/WIDTH: 9 12 "08/01/18 11:00:21" TEXT: Scaler 2
CL_FRM "RawValue" SHOWNAME POSL 2 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE ANY_INT TEXT: analog raw value
CL_FRM "In_max" SHOWNAME POSL 4 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE ANY_INT TEXT: Max raw value
CL_FRM "In_min" SHOWNAME POSL 5 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE ANY_INT TEXT: Min raw value
CL_FRM "Out_max" SHOWNAME POSL 6 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE ANY_INT TEXT: Max scaled value
CL_FRM "Out_min" SHOWNAME POSL 7 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE ANY_INT TEXT: Min scaled value
CL_FRM "ScalValue" SHOWNAME POSR 2 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE ANY_INT TEXT: scaling value
CL_FRM "Error" SHOWNAME POSR 3 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Error in input
CL_TYN SCALER_DINT, SCALER_INT, SCALER_UDINT, SCALER_UINT
CL_PRT ;
//
// SCALER_DINT
//
CL_EFB "SCALER_DINT" "General" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 9 12 "08/01/18 11:00:21" TEXT: Scaler 2
CL_FRM "RawValue" SHOWNAME POSL 2 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE DINT TEXT: analog raw value
CL_FRM "In_max" SHOWNAME POSL 4 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE DINT TEXT: Max raw value
CL_FRM "In_min" SHOWNAME POSL 5 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE DINT TEXT: Min raw value
CL_FRM "Out_max" SHOWNAME POSL 6 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE DINT TEXT: Max scaled value
CL_FRM "Out_min" SHOWNAME POSL 7 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE DINT TEXT: Min scaled value
CL_FRM "ScalValue" SHOWNAME POSR 2 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE DINT TEXT: scaling value
CL_FRM "Error" SHOWNAME POSR 3 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Error in input
CL_PRT extern"C"BOOL FB_CALL_CONV SCALER_DINT(const PTR_DINT,
...PRT const PTR_DINT,
...PRT const PTR_DINT,
...PRT const PTR_DINT,
...PRT const PTR_DINT,
...PRT PTR_DINT,
...PRT PTR_BOOL);
//
// SCALER_INT
//
CL_EFB "SCALER_INT" "General" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 9 12 "08/01/18 11:00:21" TEXT: Scaler 2
CL_FRM "RawValue" SHOWNAME POSL 2 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE INT TEXT: analog raw value
CL_FRM "In_max" SHOWNAME POSL 4 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE INT TEXT: Max raw value
CL_FRM "In_min" SHOWNAME POSL 5 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE INT TEXT: Min raw value
CL_FRM "Out_max" SHOWNAME POSL 6 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE INT TEXT: Max scaled value
CL_FRM "Out_min" SHOWNAME POSL 7 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE INT TEXT: Min scaled value
CL_FRM "ScalValue" SHOWNAME POSR 2 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE INT TEXT: scaling value
CL_FRM "Error" SHOWNAME POSR 3 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Error in input
CL_PRT extern"C"BOOL FB_CALL_CONV SCALER_INT(const PTR_INT,
...PRT const PTR_INT,
...PRT const PTR_INT,
...PRT const PTR_INT,
...PRT const PTR_INT,
...PRT PTR_INT,
...PRT PTR_BOOL);
//
// SCALER_UDINT
//
CL_EFB "SCALER_UDINT" "General" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 9 12 "08/01/18 11:00:21" TEXT: Scaler 2
CL_FRM "RawValue" SHOWNAME POSL 2 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UDINT TEXT: analog raw value
CL_FRM "In_max" SHOWNAME POSL 4 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UDINT TEXT: Max raw value
CL_FRM "In_min" SHOWNAME POSL 5 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UDINT TEXT: Min raw value
CL_FRM "Out_max" SHOWNAME POSL 6 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UDINT TEXT: Max scaled value
CL_FRM "Out_min" SHOWNAME POSL 7 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UDINT TEXT: Min scaled value
CL_FRM "ScalValue" SHOWNAME POSR 2 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE UDINT TEXT: scaling value
CL_FRM "Error" SHOWNAME POSR 3 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Error in input
CL_PRT extern"C"BOOL FB_CALL_CONV SCALER_UDINT(const PTR_UDINT,
...PRT const PTR_UDINT,
...PRT const PTR_UDINT,
...PRT const PTR_UDINT,
...PRT const PTR_UDINT,
...PRT PTR_UDINT,
...PRT PTR_BOOL);
//
// SCALER_UINT
//
CL_EFB "SCALER_UINT" "General" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 9 12 "08/01/18 11:00:21" TEXT: Scaler 2
CL_FRM "RawValue" SHOWNAME POSL 2 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: analog raw value
CL_FRM "In_max" SHOWNAME POSL 4 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: Max raw value
CL_FRM "In_min" SHOWNAME POSL 5 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: Min raw value
CL_FRM "Out_max" SHOWNAME POSL 6 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: Max scaled value
CL_FRM "Out_min" SHOWNAME POSL 7 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: Min scaled value
CL_FRM "ScalValue" SHOWNAME POSR 2 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE UINT TEXT: scaling value
CL_FRM "Error" SHOWNAME POSR 3 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Error in input
CL_PRT extern"C"BOOL FB_CALL_CONV SCALER_UINT(const PTR_UINT,
...PRT const PTR_UINT,
...PRT const PTR_UINT,
...PRT const PTR_UINT,
...PRT const PTR_UINT,
...PRT PTR_UINT,
...PRT PTR_BOOL);
//
// Elementary Function Block:  SCHEDUL
//
//                      ____________________
//                     |                    |
//                     |      SCHEDUL       |
//                     |                    |
//             WORD ---| Config             |                    
//             BOOL ---> Reset        WtRes |--- BOOL            
//             BOOL ---| Start          End |--- BOOL            
//             BOOL ---| Trm1          Sch1 |--- BOOL            
//             BOOL ---| Trm2          Sch2 |--- BOOL            
//             BOOL ---| Trm3          Sch3 |--- BOOL            
//             BOOL ---| Trm4          Sch4 |--- BOOL            
//             BOOL ---| Trm5          Sch5 |--- BOOL            
//             BOOL ---| Trm6          Sch6 |--- BOOL            
//             BOOL ---| Trm7          Sch7 |--- BOOL            
//             BOOL ---| Trm8          Sch8 |--- BOOL            
//             BOOL ---| InvD               |                    
//             TIME ---| DelT         ActDT |--- TIME            
//             WORD ---| CyclT              |                    
//                     |____________________|
//
// SCHEDUL
//
CL_EFB "SCHEDUL" "General" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 17 7 "08/01/18 11:22:54" TEXT: Scheduler
CL_FRM "Config" SHOWNAME POSL 2 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE WORD TEXT: Configuration register (Low byte : bit = 1 => output skip)
CL_FRM "Reset" SHOWNAME POSL 3 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL FP_TRG_RISING_EDGE TEXT: Reset scheduler
CL_FRM "Start" SHOWNAME POSL 4 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Start scheduling
CL_FRM "Trm1" SHOWNAME POSL 5 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: process N1 has been terminated start next
CL_FRM "Trm2" SHOWNAME POSL 6 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: process N2 has been terminated start next
CL_FRM "Trm3" SHOWNAME POSL 7 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: process N3 has been terminated start next
CL_FRM "Trm4" SHOWNAME POSL 8 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: process N4 has been terminated start next
CL_FRM "Trm5" SHOWNAME POSL 9 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: process N5 has been terminated start next
CL_FRM "Trm6" SHOWNAME POSL 10 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: process N6 has been terminated start next
CL_FRM "Trm7" SHOWNAME POSL 11 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: process N7 has been terminated start next
CL_FRM "Trm8" SHOWNAME POSL 12 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: process N8 has been terminated end of scheduling
CL_FRM "InvD" SHOWNAME POSL 13 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: invert disabled outputs
CL_FRM "DelT" SHOWNAME POSL 14 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE TIME TEXT: delay time
CL_FRM "CyclT" SHOWNAME POSL 15 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE WORD TEXT: PLC scan time 	
CL_FRM "Istate" SHOWNAME POSR 1 FP_IO_OUTPUT FP_OUTP_INTERN_STATE FP_LOC_HIDDEN INTSTATE VAL: 9 TEXT: Internal State
CL_FRM "WtRes" SHOWNAME POSR 3 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Waiting for the reset process to terminate
CL_FRM "End" SHOWNAME POSR 4 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: End of scheduling
CL_FRM "Sch1" SHOWNAME POSR 5 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Activate process N1
CL_FRM "Sch2" SHOWNAME POSR 6 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Activate process N2
CL_FRM "Sch3" SHOWNAME POSR 7 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Activate process N3
CL_FRM "Sch4" SHOWNAME POSR 8 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Activate process N4
CL_FRM "Sch5" SHOWNAME POSR 9 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Activate process N5
CL_FRM "Sch6" SHOWNAME POSR 10 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Activate process N6
CL_FRM "Sch7" SHOWNAME POSR 11 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Activate process N7
CL_FRM "Sch8" SHOWNAME POSR 12 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Activate process N8
CL_FRM "ActDT" SHOWNAME POSR 14 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE TIME TEXT: Current delay time
CL_PRT extern"C"BOOL FB_CALL_CONV SCHEDUL(const PTR_WORD,
...PRT const PTR_BOOL,
...PRT const PTR_BOOL,
...PRT const PTR_BOOL,
...PRT const PTR_BOOL,
...PRT const PTR_BOOL,
...PRT const PTR_BOOL,
...PRT const PTR_BOOL,
...PRT const PTR_BOOL,
...PRT const PTR_BOOL,
...PRT const PTR_BOOL,
...PRT const PTR_BOOL,
...PRT const PTR_TIME,
...PRT const PTR_WORD,
...PRT PTR_Istat_SCHEDUL,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_TIME);
//
// Elementary Function Block:  STAPROT
//
//                      ____________________
//                     |                    |
//                     |      STAPROT       |
//                     |                    |
//         STPROTTB ---| StaDebl----StaDebl |--- STPROTTB
//       STAPROTTAB ---| SPrMask----SPrMask |--- STAPROTTAB
//       STAPROTTAB ---| SPrImit----SPrImit |--- STAPROTTAB
//       STAPROTTAB ---| SPrTest----SPrTest |--- STAPROTTAB
//                     |                    |                    
//             WORD ---| SDeblPt1--SDeblPt1 |--- WORD
//             WORD ---| SMaskPt1--SMaskPt1 |--- WORD
//             WORD ---| SImitPt1--SImitPt1 |--- WORD
//             WORD ---| STestPt1--STestPt1 |--- WORD
//                     |                    |                    
//             WORD ---| SDeblPt2--SDeblPt2 |--- WORD
//             WORD ---| SMaskPt2--SMaskPt2 |--- WORD
//             WORD ---| SImitPt2--SImitPt2 |--- WORD
//             WORD ---| STestPt2--STestPt2 |--- WORD
//                     |                    |                    
//       STAPROTTAB ---| SPrSgIn    SPrSgOu |--- STAPROTTAB      
//                     |            SProtTb |--- STAPROTTAB      
//         STPROTTB ---| SPrConf    SPrtTst |--- STAPROTTAB      
//         STPROTTB ---| SPrTMCf    SPrtPrm |--- STPROTTB        
//         STPROTTB ---| SPrSnCf            |                    
//             WORD ---| StaStat            |                    
//                     |              Sound |--- BOOL            
//             BOOL ---| SGlbDbl    Warning |--- BOOL            
//             BOOL ---| S_TMDbl      Error |--- BOOL            
//                     |                    |                    
//         STPROTTB ---| SPrSpCf            |                    
//             BOOL ---| S_SpDbl            |                    
//                     |____________________|
//
// STAPROT
//
CL_EFB "STAPROT" "Station" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 30 11 "08/01/18 11:22:54" TEXT: Handling station protection and start disable signals.
CL_FRM "SPrSgIn" SHOWNAME POSL 17 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE STAPROTTAB TEXT: station protection inp.signals
CL_FRM "SPrConf" SHOWNAME POSL 19 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE STPROTTB TEXT: sta.pr.signals configuration
CL_FRM "SPrTMCf" SHOWNAME POSL 20 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE STPROTTB TEXT: sta.pr.TM deblocking configuration
CL_FRM "SPrSnCf" SHOWNAME POSL 21 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE STPROTTB TEXT: sta.pr.sound signal configuration
CL_FRM "StaStat" SHOWNAME POSL 22 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE WORD TEXT: station statusword
CL_FRM "SGlbDbl" SHOWNAME POSL 24 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: global deblocking station alarms
CL_FRM "S_TMDbl" SHOWNAME POSL 25 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: TM deblocking station alarms
CL_FRM "SPrSpCf" SHOWNAME POSL 27 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE STPROTTB TEXT: sta.pr.spec.deblocking configuration
CL_FRM "S_SpDbl" SHOWNAME POSL 28 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Spec.deblocking station alarms
CL_FRM "Istate" SHOWNAME POSR 1 FP_IO_OUTPUT FP_OUTP_INTERN_STATE FP_LOC_HIDDEN INTSTATE VAL: 64 TEXT: Internal State
CL_FRM "StaDebl" SHOWNAME POSR 2 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE STPROTTB TEXT: individual deblocking signals
CL_FRM "SPrMask" SHOWNAME POSR 3 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE STAPROTTAB TEXT: station protection mask flags
CL_FRM "SPrImit" SHOWNAME POSR 4 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE STAPROTTAB TEXT: station protection imitation flags
CL_FRM "SPrTest" SHOWNAME POSR 5 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE STAPROTTAB TEXT: station protection test flags
CL_FRM "SDeblPt1" SHOWNAME POSR 7 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE WORD TEXT: deblocking station prot.sign.ptr.1
CL_FRM "SMaskPt1" SHOWNAME POSR 8 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE WORD TEXT: station prot.sign.mask ptr.1
CL_FRM "SImitPt1" SHOWNAME POSR 9 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE WORD TEXT: station prot.sign.imitation ptr.1
CL_FRM "STestPt1" SHOWNAME POSR 10 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE WORD TEXT: station prot.sign.test mode ptr.1
CL_FRM "SDeblPt2" SHOWNAME POSR 12 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE WORD TEXT: deblocking station prot.sign.ptr.2
CL_FRM "SMaskPt2" SHOWNAME POSR 13 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE WORD TEXT: station prot.sign.mask ptr.2
CL_FRM "SImitPt2" SHOWNAME POSR 14 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE WORD TEXT: station prot.sign.imitation ptr.2
CL_FRM "STestPt2" SHOWNAME POSR 15 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE WORD TEXT: station prot.sign.test mode ptr.2
CL_FRM "SPrSgOu" SHOWNAME POSR 17 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE STAPROTTAB TEXT: station protection outp.signals
CL_FRM "SProtTb" SHOWNAME POSR 18 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE STAPROTTAB TEXT: station protection table
CL_FRM "SPrtTst" SHOWNAME POSR 19 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE STAPROTTAB TEXT: station protection table test mode
CL_FRM "SPrtPrm" SHOWNAME POSR 20 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE STPROTTB TEXT: station protection table prim.sign.
CL_FRM "Sound" SHOWNAME POSR 23 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Sound signal
CL_FRM "Warning" SHOWNAME POSR 24 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Warning signal
CL_FRM "Error" SHOWNAME POSR 25 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Error flag
CL_PRT extern"C"BOOL FB_CALL_CONV STAPROT(const PTR_STAPROTTAB,
...PRT const PTR_STPROTTB,
...PRT const PTR_STPROTTB,
...PRT const PTR_STPROTTB,
...PRT const PTR_WORD,
...PRT const PTR_BOOL,
...PRT const PTR_BOOL,
...PRT const PTR_STPROTTB,
...PRT const PTR_BOOL,
...PRT PTR_Istat_STAPROT,
...PRT PTR_STPROTTB,
...PRT PTR_STAPROTTAB,
...PRT PTR_STAPROTTAB,
...PRT PTR_STAPROTTAB,
...PRT PTR_WORD,
...PRT PTR_WORD,
...PRT PTR_WORD,
...PRT PTR_WORD,
...PRT PTR_WORD,
...PRT PTR_WORD,
...PRT PTR_WORD,
...PRT PTR_WORD,
...PRT PTR_STAPROTTAB,
...PRT PTR_STAPROTTAB,
...PRT PTR_STAPROTTAB,
...PRT PTR_STPROTTB,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_BOOL);
//
// Elementary Function Block:  StFlgSet
//
//                      ____________________
//                     |                    |
//                     |      StFlgSet      |
//                     |                    |
//             WORD ---| StaReg------StaReg |--- WORD
//             WORD ---| Mask               |                    
//             UINT ---| BIT_NO             |                    
//                     |____________________|
//
// StFlgSet
//
CL_EFB "StFlgSet" "General" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 6 9 "08/01/18 11:00:21" TEXT: Set a bit in a statusword, before doing this, specified bits
...TXT             can be cleared with a mask.
CL_FRM "Mask" SHOWNAME POSL 3 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE WORD TEXT: mask for clearing specified bits in the register
CL_FRM "BIT_NO" SHOWNAME POSL 4 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: Numbers of register bit
CL_FRM "StaReg" SHOWNAME POSR 2 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE WORD TEXT: status register
CL_PRT extern"C"BOOL FB_CALL_CONV StFlgSet(const PTR_WORD,
...PRT const PTR_UINT,
...PRT PTR_WORD);
//
// Elementary Function Block:  TIM_SYNC
//
//                      ____________________
//                     |                    |
//                     |      TIM_SYNC      |
//                     |                    |
//        TOD_CLOCK ---| ActTime----ActTime |--- TOD_CLOCK
//        TOD_CLOCK ---| TOD_Clk----TOD_Clk |--- TOD_CLOCK
//                     |                    |                    
//                     |             UnSucc |--- BOOL            
//             UINT ---| MaxDiff            |                    
//             BOOL ---| LiveSign           |                    
//                     |                    |                    
//             TIME ---| MaxTSet            |                    
//             TIME ---| LiveTime           |                    
//                     |            GoTimer |--- BOOL            
//             BOOL ---| Q          SetTime |--- TIME            
//                     |____________________|
//
// TIM_SYNC
//
CL_EFB "TIM_SYNC" "General" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 14 10 "08/01/18 11:22:54" TEXT: Time syncronization
CL_FRM "MaxDiff" SHOWNAME POSL 6 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: max time difference in second
CL_FRM "LiveSign" SHOWNAME POSL 7 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Communication live signa
CL_FRM "MaxTSet" SHOWNAME POSL 9 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE TIME TEXT: Time setting Time
CL_FRM "LiveTime" SHOWNAME POSL 10 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE TIME TEXT: Live signal TimOut
CL_FRM "Q" SHOWNAME POSL 12 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: SetTimeTON is active
CL_FRM "Istate" SHOWNAME POSR 1 FP_IO_OUTPUT FP_OUTP_INTERN_STATE FP_LOC_HIDDEN INTSTATE VAL: 18 TEXT: Internal State
CL_FRM "ActTime" SHOWNAME POSR 2 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE TOD_CLOCK TEXT: Actual time from main PLC
CL_FRM "TOD_Clk" SHOWNAME POSR 3 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE TOD_CLOCK TEXT: TOD time
CL_FRM "UnSucc" SHOWNAME POSR 5 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Unuccessfuly time syncronize
CL_FRM "GoTimer" SHOWNAME POSR 11 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: start of setting timer
CL_FRM "SetTime" SHOWNAME POSR 12 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE TIME TEXT: setting Time of the timer
CL_PRT extern"C"BOOL FB_CALL_CONV TIM_SYNC(const PTR_UINT,
...PRT const PTR_BOOL,
...PRT const PTR_TIME,
...PRT const PTR_TIME,
...PRT const PTR_BOOL,
...PRT PTR_Istat_TIM_SYNC,
...PRT PTR_TOD_CLOCK,
...PRT PTR_TOD_CLOCK,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_TIME);
//
// Elementary Function:  TMST
//
//                      ____________________
//                     |                    |
//                     |        TMST        |
//                     |                    |
//        TOD_CLOCK ---| Clock              |--- WORD            
//                     |____________________|
//
// TMST
//
CL_EFB "TMST" "General" ANYPIN_NO FBTK_EFB_FUNCT HEIGHT/WIDTH: 4 9 "08/01/18 11:00:21" TEXT: Creating time stamp from the current TOD clock value.
CL_FRM "Clock" SHOWNAME POSL 2 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE TOD_CLOCK TEXT: TOD clock
CL_FRM "TimStamp" HIDENAME POSR 2 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE WORD TEXT: time stamp
CL_PRT extern"C"BOOL FB_CALL_CONV TMST(const PTR_TOD_CLOCK,
...PRT PTR_WORD);
//
// Elementary Function Block:  WRD4_BIT
//
//                      ____________________
//                     |                    |
//                     |      WRD4_BIT      |
//                     |                    |
//  AUX_1_EVNT_REGS ---| WORD4       BOOL64 |--- AUX_1_EVNT_MESS 
//                     |                    |                    
//                     |              Error |--- BOOL            
//                     |               Diag |--- WORD            
//                     |____________________|
//
// WRD4_BIT
//
CL_EFB "WRD4_BIT" "General" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 7 9 "08/01/18 11:00:21" TEXT: Copying 4 words to table of BOOL-s.
CL_FRM "WORD4" SHOWNAME POSL 2 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE AUX_1_EVNT_REGS TEXT: Four words to be converted
CL_FRM "BOOL64" SHOWNAME POSR 2 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE AUX_1_EVNT_MESS TEXT: Destination block of BOOL-s
CL_FRM "Error" SHOWNAME POSR 4 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Error flag
CL_FRM "Diag" SHOWNAME POSR 5 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE WORD TEXT: Diagnostics
CL_PRT extern"C"BOOL FB_CALL_CONV WRD4_BIT(const PTR_AUX_1_EVNT_REGS,
...PRT PTR_AUX_1_EVNT_MESS,
...PRT PTR_BOOL,
...PRT PTR_WORD);
//
// Elementary Function Block:  WR_BIT
//
//                      ____________________
//                     |                    |
//                     |       WR_BIT       |
//                     |                    |
//             WORD ---| REGISTER--REGISTER |--- WORD
//             UINT ---| BIT_NO             |                    
//             BOOL ---| SET                |                    
//             BOOL ---| RESET              |                    
//                     |____________________|
//
// WR_BIT
//
CL_EFB "WR_BIT" "General" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 7 11 "08/01/18 11:00:21" TEXT: Set or reset a bit in a word
CL_FRM "BIT_NO" SHOWNAME POSL 3 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE UINT TEXT: Numbers of register bit
CL_FRM "SET" SHOWNAME POSL 4 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Set bit in a words
CL_FRM "RESET" SHOWNAME POSL 5 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Reset
CL_FRM "REGISTER" SHOWNAME POSR 2 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE WORD TEXT: setting register
CL_PRT extern"C"BOOL FB_CALL_CONV WR_BIT(const PTR_UINT,
...PRT const PTR_BOOL,
...PRT const PTR_BOOL,
...PRT PTR_WORD);
//
// Elementary Function Block:  ZUMMER
//
//                      ____________________
//                     |                    |
//                     |       ZUMMER       |
//                     |                    |
//             BOOL ---| Debl1         Zumm |--- BOOL            
//             BOOL ---| Debl2              |                    
//             BOOL ---| Debl3       DblOut |--- BOOL            
//                     |                    |                    
//             BOOL ---| Enable      ZOnImp |--- BOOL            
//                     |                    |                    
//             BOOL ---| In                 |                    
//                   : |                    |                    
//             BOOL ---| In                 |                    
//                     |____________________|
//
// ZUMMER
//
CL_EFB "ZUMMER" "General" ANYPIN_NO FBTK_EFB_EXT HEIGHT/WIDTH: 11 8 "08/01/18 11:22:54" TEXT: Control of station operator zummer
CL_FRM "Debl1" SHOWNAME POSL 2 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Deblock impulse 1 (from BRU)
CL_FRM "Debl2" SHOWNAME POSL 3 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Deblock impulse 2 (from MDP1)
CL_FRM "Debl3" SHOWNAME POSL 4 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Deblock impulse 3 (from MDP2)
CL_FRM "Enable" SHOWNAME POSL 6 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Operator zummer is in enalble
CL_FRM "nin" SHOWNAME POSL 1 FP_IO_INPUT FP_INP_IMMEDIATE_NIN FP_LOC_HIDDEN INT VAL: 2 TEXT: extensible input count
CL_FRM "Istate" SHOWNAME POSR 1 FP_IO_OUTPUT FP_OUTP_INTERN_STATE FP_LOC_HIDDEN INTSTATE VAL: 2 TEXT: Internal State
CL_FRM "Zumm" SHOWNAME POSR 2 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Zummer is switched on
CL_FRM "DblOut" SHOWNAME POSR 4 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Zummer deblock signal
CL_FRM "ZOnImp" SHOWNAME POSR 6 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Zummer in impulse
CL_FRM "In1" SHOWNAME POSL 8 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: extensible inputs
CL_FRM "In2" SHOWNAME POSL 9 FP_IO_INPUT FP_INP_EXTENSIBLE FP_LOC_OUTSIDE BOOL VAL: 24 TEXT: extensible inputs
CL_PRT extern"C"BOOL FB_CALL_CONV ZUMMER(const PTR_BOOL,
...PRT const PTR_BOOL,
...PRT const PTR_BOOL,
...PRT const PTR_BOOL,
...PRT INT,
...PRT PTR_Istat_ZUMMER,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT PTR_BOOL,
...PRT ...);
//
// Elementary Function Block:  ZUMM_AUX
//
//                      ____________________
//                     |                    |
//                     |      ZUMM_AUX      |
//                     |                    |
//             WORD ---| Inp_word           |                    
//             BOOL ---| Typ            Clk |--- BOOL            
//                     |____________________|
//
// ZUMM_AUX
//
CL_EFB "ZUMM_AUX" "General" ANYPIN_NO FBTK_EFB HEIGHT/WIDTH: 5 6 "08/01/18 11:22:54" TEXT: Auxiliary function block for ZUMMER using
CL_FRM "Inp_word" SHOWNAME POSL 2 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE WORD TEXT: zummer input word
CL_FRM "Typ" SHOWNAME POSL 3 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Typ = 1 -> F_Trig
CL_FRM "Istate" SHOWNAME POSR 1 FP_IO_OUTPUT FP_OUTP_INTERN_STATE FP_LOC_HIDDEN INTSTATE VAL: 2 TEXT: Internal State
CL_FRM "Clk" SHOWNAME POSR 3 FP_IO_OUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: Output clock
CL_PRT extern"C"BOOL FB_CALL_CONV ZUMM_AUX(const PTR_WORD,
...PRT const PTR_BOOL,
...PRT PTR_Istat_ZUMM_AUX,
...PRT PTR_BOOL);
//
// Elementary Function Block:  ZUMM_TX
//
//                      ____________________
//                     |                    |
//                     |      ZUMM_TX       |
//                     |                    |
//             WORD ---| Zumm----------Zumm |--- WORD
//                     |                    |                    
//             BOOL ---| In_Clk             |                    
//                   : |                    |                    
//             BOOL ---| In_Clk             |                    
//                     |____________________|
//
// ZUMM_TX
//
CL_EFB "ZUMM_TX" "General" ANYPIN_NO FBTK_EFB_EXT HEIGHT/WIDTH: 7 7 "08/01/18 11:00:21" TEXT: Zummer send to main PLC
CL_FRM "nin" SHOWNAME POSL 1 FP_IO_INPUT FP_INP_IMMEDIATE_NIN FP_LOC_HIDDEN INT VAL: 2 TEXT: extensible input count
CL_FRM "Zumm" SHOWNAME POSR 2 FP_IO_INOUTPUT FP_OUTP_NORMAL FP_LOC_OUTSIDE WORD TEXT: Zummer sender
CL_FRM "In_Clk1" SHOWNAME POSL 4 FP_IO_INPUT FP_INP_NORMAL FP_LOC_OUTSIDE BOOL TEXT: extensible inputs
CL_FRM "In_Clk2" SHOWNAME POSL 5 FP_IO_INPUT FP_INP_EXTENSIBLE FP_LOC_OUTSIDE BOOL VAL: 28 TEXT: extensible inputs
CL_PRT extern"C"BOOL FB_CALL_CONV ZUMM_TX(INT,
...PRT PTR_WORD,
...PRT ...);
CR_END *
